## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)
sudo: required
language: c

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
## Save OPL dir, go to previous dir and save ENV dir
- export OPL_DIR=$(pwd)
- cd ../
- export ENV_DIR=$(pwd)

install:
## Dependencies
- sudo apt-get install -yqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev

before_script:
## Make cleanup, just for prevent anything
- cd ${ENV_DIR}/
- rm -rf ${ENV_DIR}/gsKit/ ${ENV_DIR}/ps2eth/ ${ENV_DIR}/ps2toolchain/ ${ENV_DIR}/ps2-packer/ ${ENV_DIR}/ps2sdk-ports/

## Set up some variables
- export PS2DEV=${ENV_DIR}/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
- export PS2ETH=${PS2DEV}/ps2eth
- export GSKIT=${PS2DEV}/gsKit
- export LANG=C
- export LC_ALL=C

## Clone all
- cd ${ENV_DIR}/
- git clone --quiet https://github.com/ps2dev/ps2toolchain.git ${ENV_DIR}/ps2toolchain/
- git clone --quiet https://github.com/ps2dev/ps2sdk-ports.git ${ENV_DIR}/ps2sdk-ports/
- git clone --quiet https://github.com/ps2dev/ps2eth ${ENV_DIR}/ps2eth/
- git clone --quiet https://github.com/ps2dev/gsKit.git ${ENV_DIR}/gsKit/
- git clone --quiet https://github.com/ps2dev/ps2-packer.git ${ENV_DIR}/ps2-packer/
- chmod +x $(find . -name \*sh)

## ps2dev/PS2Toolchain
- cd ${ENV_DIR}/ps2toolchain/
- bash ./toolchain.sh

## ps2dev/PS2SDKPorts/zlib
- cd ${ENV_DIR}/ps2sdk-ports/zlib/
- make; make install

## ps2dev/PS2SDKPorts/libpng
- cd ${ENV_DIR}/ps2sdk-ports/libpng/
- make; make install

## ps2dev/PS2SDKPorts/libjpeg
- cd ${ENV_DIR}/ps2sdk-ports/libjpeg/
- make; make install

## ps2dev/PS2SDKPorts/freetype
- cd ${ENV_DIR}/ps2sdk-ports/freetype-2.4.12/
- bash ./SetupPS2.sh

## ps2dev/PS2ETH
- cd ${ENV_DIR}/ps2eth/
- make
- sudo mkdir -p /usr/lib/ps2dev/ps2eth
- sudo tar c $(find . -name \*irx) | sudo tar x -C /usr/lib/ps2dev/ps2eth

## ps2dev/gsKit
- cd ${ENV_DIR}/gsKit/
- make; make install

## ps2dev/PS2Packer
- cd ${ENV_DIR}/ps2-packer/
- make; make install

script:
## Let's build Open PS2 Loader Release!
- cd ${OPL_DIR}/
- bash ./make_changelog.sh
- bash ./lng_pack.sh
- git add -A
- make release

## [TEMPLATE] Deploy OPL to Github Releases
# 1. Clone this repository
# 2. Copy '.travis.yml' to '.travis-original.yml' (you will need it after)
# 3. Install Travis Client <https://github.com/travis-ci/travis.rb#installation>
# 4. Run command: $(travis setup releases)
#    After follow all previous steps, pickup ONLY the "secure" line
#    and change it on '.travis-original.yml'
# 5. Move '.travis-original.yml' to '.travis.yml'
# 6. Commit it
## NOTE: You need to configure TravisCI before anything <https://travis-ci.org/>

## Deploy OPL to Github Releases
deploy:
  provider: releases
  skip_cleanup: true
#  api_key:
#    secure: [PUT YOUR NEW SECURE API KEY HERE]
  file_glob: true
  file:
    - "${OPL_DIR}/OPNPS2LD-*.zip"
    - "${OPL_DIR}/OPNPS2LD_LANGS-*.zip"
  on:
    branch: master
