name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk
    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Compile -> make clean release
      run: |
        make --trace clean release
    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: EX4OPL
        path: |
          EX4OPL-*.ELF
    - name: Upload release artifact info
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: INFO
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md
  build-variants:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    strategy:
      matrix:
        rtl: ["", RTL=1]
        pademu: ["", PADEMU=1]
        igs: ["", IGS=1]
        t10k: ["", DTL_T10000=1]
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git
    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
      run: |
        make --trace ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
        mv opl.elf OPNPS2LD-${{ steps.version.outputs.version }}-${{ matrix.t10k }}-${{ matrix.igs }}-${{ matrix.pademu }}-${{ matrix.rtl }}.ELF
    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload variants artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: EX4OPL-VARIANTS
        path: |
          EX4OPL*.ELF
  release:
    needs: [build, build-variants]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Download release artifact
      uses: actions/download-artifact@v1
      with:
        name: EX4OPL

    - name: Download variants artifact
      uses: actions/download-artifact@v1
      with:
        name: EX4OPL-VARIANTS

    - name: Download info artifact
      uses: actions/download-artifact@v1
      with:
        name: INFO

    - name: Prepare artifacts for release
      run: |
        cp INFO/* EX4OPL/
        cp INFO/* EX4OPL-VARIANTS/
        7z a -t7z EX4OPL-${{ steps.version.outputs.version }}.7z EX4OPL/*
        7z a -t7z EX4OPL-${{ steps.version.outputs.version }}.7z EX4OPL-VARIANTS/*
    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "${{ steps.version.outputs.version }}"
        files: |
          EX4OPL-${{ steps.version.outputs.version }}.7z
          EX4OPL-VARIANTS-${{ steps.version.outputs.version }}.7z
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "${{ steps.version.outputs.version }}"
        files: |
          EX4OPL-${{ steps.version.outputs.version }}.7z
          EXO4OPL-VARIANTS-${{ steps.version.outputs.version }}.7z
